### ISSUE TITLE
NSData seems to decode as null...

### ISSUE THREAD

**Issue by mbalex99** [dashevo/TinyCborObjc#5]
Thanks so much for adding the decoding. I've run into an issue when I have an `NSDictionary` that has some data and primitives but however everything is coming back null

```Objc
- (void)testJSONDictionary {
    // random NSData
    size_t outBufferSize = 1024;
    void * bytes = malloc(outBufferSize);
    NSData *data = [NSData dataWithBytes:bytes length:outBufferSize];
    free(bytes);
    // just creating some random data. 
    
    NSError *error = nil;
    
    NSDictionary *json = @{
                           @"_id": @"max",
                           @"data": data
                           };
    
    id encoded = [json ds_cborEncodedObject];
    NSLog(@"Encoded %@", encoded);
    
    id decoded = [encoded ds_decodeCborWithOutBufferSize:outBufferSize
                                                error:&error];
    
    NSLog(@"Decoded %@", decoded);
    NSLog(@"Error %@", error);
}
```

Here's the Debug Console output

```
2019-04-02 09:42:04.260888-0700 xctest[44666:4491604] Encoded (null)
2019-04-02 09:42:04.261241-0700 xctest[44666:4491604] Decoded (null)
2019-04-02 09:42:04.261325-0700 xctest[44666:4491604] Error (null)
```
Everything seems to be null. Am I doing something wrong?

**Comment by podkovyrin** [comment]
The problem here is JSON can't contain raw `NSData` object (JSON format supports only the following Foundation types: `NSDictionary`, `NSArray`, `NSString`, `NSNumber` and `NSNull`). So if you need to include `NSData` into your JSON object you will have to encode that data, for instance using Base64 encoding:
```objective-c
NSDictionary *json = @{
    @"_id": @"max",
    @"data": [data base64EncodedStringWithOptions:kNilOptions]
};
```
After fixing it you will face another issue. The `outBufferSize` is too small to contain decoded JSON string (because `json` already contains data that is `outBufferSize`-long). Providing an appropriate buffer size for the decoded data is not an easy task because you need to guess the resulting size of decoded data which is unknown basically. In this simple case, you can just guess the `outBufferSize` parameter as follows:
```objective-c
id decoded = [encoded ds_decodeCborWithOutBufferSize:outBufferSize * 2
                                               error:&error];
```
For more complicated cases I use recursion to guess the need `outBufferSize`:
```objective-c
static _Nullable id DecodeCborData(NSData *data, size_t outBufferSize, NSError *_Nullable __autoreleasing *error) {
    const size_t MAX_BUFFER_SIZE = 1024 * 1024 * 4; // 4 Mb

    NSError *decodingError = nil;
    id decoded = [data ds_decodeCborWithOutBufferSize:outBufferSize error:&decodingError];
    if ([decodingError.domain isEqualToString:DSTinyCborDecodingErrorDomain] &&
        decodingError.code == 4 /* CborErrorIO */ &&
        outBufferSize <= MAX_BUFFER_SIZE) {
        return DecodeCborData(data, outBufferSize * 2, error);
    }

    if (error != NULL) {
        *error = decodingError;
    }

    return decoded;
}

// Usage:
const size_t INITIAL_BUFFER_SIZE = 1024; // 1 Kb
id decoded = DecodeCborData(data, INITIAL_BUFFER_SIZE, error);
```
I'm working on simplifying decoding API without the need for providing `outBufferSize` at all.

Also, I fixed an important bug in decoding, so please use the new version 0.3.1.

**Comment by mbalex99** [comment]
I thought this was primarily around CBOR not JSON. Isn't CBOR's spec allow for byte strings to be embedded as a payload?

**Comment by podkovyrin** [comment]
Yes, that's correct. But for now, we don't support tags and embedded byte strings. So it is more like JSON-compliant CBOR encoding/decoding. 
You can follow this example to add needed functionality https://github.com/intel/tinycbor/blob/master/tools/json2cbor/json2cbor.c

**Comment by podkovyrin** [comment]
@mbalex99 Version `0.4.1` supports encoding and decoding CBOR with NSData payload

**Comment by mbalex99** [comment]
@podkovyrin thank you so much!
